name: Build and Deploy Staging

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, uat]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Create .env file
        env:
          ENV_FILE_CONTENTS: ${{ vars.UAT_SECRETS }}
        run: |
          printf "%s" "$ENV_FILE_CONTENTS" > .env

      - name: Install Dependencies
        run: |
          pnpm install
          cd ./apps/core
          pnpm install
          ls
          pwd
          cd ./../..
          pwd
          ls

      - name: Build pollpapa-core
        run: |
          turbo build --filter=pollpapa-core -vvv
          ls
          pwd

      - name: Deploy
        run: /home/ubuntu/build.sh

      - name: Print Folders & Paths
        run: |
          cd /var/www/anketa-backend/node_modules/.pnpm/@adminjs+design-system@4.1.1_@babel+core@7.26.0_@types+react@18.3.12_prop-types@15.8.1_react-_i7l5qhoewreojbwkv7pcog3coi
          echo "Current Directory1: $(pwd)"
          ls 
          cd /var/www/anketa-backend/node_modules/.pnpm/@adminjs+design-system@4.1.1_@babel+core@7.26.0_@types+react@18.3.12_prop-types@15.8.1_react-_i7l5qhoewreojbwkv7pcog3coi/node_modules/@adminjs/design-system/build/
          echo "Current Directory2: $(pwd)"
          ls 
          cd /var/www/anketa-backend/node_modules/.pnpm/@adminjs+design-system@4.1.1_@babel+core@7.26.0_@types+react@18.3.12_prop-types@15.8.1_react-_i7l5qhoewreojbwkv7pcog3coi/node_modules/@adminjs/design-system/build/molecules/drawer/
          echo "Current Directory3: $(pwd)"
          ls 
          echo ">>> Test1: $(pwd)"
          ls -la /var/www/anketa-backend/node_modules/.pnpm/@adminjs+design-system@4.1.1_@babel+core@7.26.0_@types+react@18.3.12_prop-types@15.8.1_react-_i7l5qhoewreojbwkv7pcog3coi/node_modules/@adminjs/design-system/build/molecules/drawer/
            

